### ISSUE TITLE
Unhandled rejection TypeError

### ISSUE THREAD

**Issue by vijaycs** [dreamzmaster/gulp-sitespeedio#18]
I used Gulp-sitespeedio for profiling a web app. But i struck on the below error.

TypeError: /Users/vijay/node_modules/sitespeed.io/lib/plugins/html/templates/pages.pug:8
    6|     - p = pageInfo.data.pagexray ? pageInfo.data.pagexray.pageSummary : {}
    7|     - t = p.contentTypes || {javascript: {transferSize: ''}, css: {transferSize: ''}, image: {transferSize: ''}}
  > 8|     - display = options.urlsMetaData[url] ? options.urlsMetaData[url].alias : url
    9|     tr
    10|       td.url.pagesurl(data-title='URL')
    11|         a(href= pageInfo.path + 'index.html')= decodeURIComponent(display)

Cannot read property 'https://www.sitespeed.io' of undefined
    6|     - p = pageInfo.data.pagexray ? pageInfo.data.pagexray.pageSummary : {}
    7|     - t = p.contentTypes || {javascript: {transferSize: ''}, css: {transferSize: ''}, image: {transferSize: ''}}
  > 8|     - display = options.urlsMetaData[url] ? options.urlsMetaData[url].alias : url
    9|     tr
    10|       td.url.pagesurl(data-title='URL')
    11|         a(href= pageInfo.path + 'index.html')= decodeURIComponent(display)

Cannot read property 'https://www.sitespeed.io' of undefined
    at Object.eval (eval at wrap (/Users/vijay/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:144:31)
    at Object.pug_interp [as rows] (eval at wrap (/Users/vijay/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:183:4)
    at eval (eval at wrap (/Users/vijay/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:320:19)
    at template (eval at wrap (/Users/vijay/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:353:184)
    at Object.renderTemplate (/Users/vijay/node_modules/sitespeed.io/lib/plugins/html/renderer.js:28:37)
    at HTMLBuilder._renderSummaryPage (/Users/vijay/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:196:67)
    at Object.keys.map (/Users/vijay/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:104:27)
    at Array.map (native)
    at HTMLBuilder.render (/Users/vijay/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:104:8)
    at Object.close (/Users/vijay/node_modules/sitespeed.io/lib/plugins/html/index.js:26:29)
    at Promise.resolve.filter.map (/Users/vijay/node_modules/sitespeed.io/lib/sitespeed.js:43:49)
    at tryCatcher (/Users/vijay/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/vijay/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/Users/vijay/node_modules/bluebird/js/release/promise_array.js:113:31)
    at MappingPromiseArray.init (/Users/vijay/node_modules/bluebird/js/release/promise_array.js:77:10)
    at MappingPromiseArray._asyncInit (/Users/vijay/node_modules/bluebird/js/release/map.js:30:10)

And the parameter used in the config file is,

({
  urls: ['https://www.sitespeed.io'],

	depth: 0,
	browsertime: {
    browser: 'chrome',
		connectivity: 'cable',
		iterations: 2,
  }
  })
}

I'm breaking my head for a week. 

Could you help on resolving the above issue.

**Comment by dreamzmaster** [comment]
my fault this should be
``
connectivity: {
  profile: 'cable'
}
``
