### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by valguss** [dreamzmaster/gulp-sitespeedio#8]
I'm currently getting the following exception:

```
Catched an uncaught exception:TypeError: Cannot read property 'har' of undefinedTypeError: Cannot read property 'har' of undefined
    at GraphiteCollector._getMeta (/Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/lib/graphite/graphiteCollector.js:84:15)
    at GraphiteCollector.collect (/Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/lib/graphite/graphiteCollector.js:70:22)
    at Object.exports.task (/Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/lib/postTasks/sendToGraphite.js:17:32)
    at /Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/lib/analyzeOneSite.js:181:32
    at /Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/node_modules/async/lib/async.js:718:13
    at async.forEachOf.async.eachOf (/Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/node_modules/async/lib/async.js:233:13)
    at _parallel (/Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/node_modules/async/lib/async.js:731:9)
    at AnalyzeOneSite._runPostTasks (/Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/lib/analyzeOneSite.js:260:9)
    at /Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/lib/analyzeOneSite.js:59:12
    at fn (/Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/node_modules/async/lib/async.js:746:34)
    at /Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/node_modules/async/lib/async.js:1213:16
    at /Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/node_modules/async/lib/async.js:166:37
    at /Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/node_modules/async/lib/async.js:706:43
    at /Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/node_modules/async/lib/async.js:167:37
    at /Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/node_modules/async/lib/async.js:1209:30
```

Here's my task config:

```
gulp.task('sitespeed', sitespeedio({
            urls: ['http://www.sitespeed.io', 'http://www.sitespeed.io/faq/'],
            browser: 'chrome',
            connection: 'cable',
            graphiteHost: 'localhost',
            graphitePort: 2003,
            graphiteNamespace: 'sitespeed'
}));
```

I'm using Node 4.2.6 and NPM 2.14.12

Here's the full process stack:

```
/usr/local/bin/node /usr/local/lib/node_modules/gulp/bin/gulp.js --color --gulpfile /Users/tom/Sites/FestiveLights/gulpfile.js sitespeed
[10:30:44] Using gulpfile ~/Sites/FestiveLights/gulpfile.js
[10:30:44] Starting 'sitespeed'...
[10:30:44] Analyze your site’s web performance
info: OS: 'darwin 15.2.0', Node.js: 'v4.2.6', sitespeed.io: '3.11.3', PhantomJS: '1.9.8', java: '1.6.0_65', browsertime: '0.12.2'
info: Will analyze 2 pages
info: Running YSlow for http://www.sitespeed.io [phantomjs]
info: Running YSlow for http://www.sitespeed.io/faq/ [phantomjs]
Starting proxy on port 2001, will wait at most 15000 ms
info: Done analyzing urls
Catched an uncaught exception:TypeError: Cannot read property 'har' of undefinedTypeError: Cannot read property 'har' of undefined
Stopping proxy
    at GraphiteCollector._getMeta (/Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/lib/graphite/graphiteCollector.js:84:15)
    at GraphiteCollector.collect (/Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/lib/graphite/graphiteCollector.js:70:22)
    at Object.exports.task (/Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/lib/postTasks/sendToGraphite.js:17:32)
    at /Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/lib/analyzeOneSite.js:181:32
    at /Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/node_modules/async/lib/async.js:718:13
    at async.forEachOf.async.eachOf (/Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/node_modules/async/lib/async.js:233:13)
    at _parallel (/Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/node_modules/async/lib/async.js:731:9)
    at AnalyzeOneSite._runPostTasks (/Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/lib/analyzeOneSite.js:260:9)
    at /Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/lib/analyzeOneSite.js:59:12
    at fn (/Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/node_modules/async/lib/async.js:746:34)
    at /Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/node_modules/async/lib/async.js:1213:16
    at /Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/node_modules/async/lib/async.js:166:37
    at /Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/node_modules/async/lib/async.js:706:43
    at /Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/node_modules/async/lib/async.js:167:37
    at /Users/tom/Sites/FestiveLights/node_modules/gulp-sitespeedio/node_modules/sitespeed.io/node_modules/async/lib/async.js:1209:30

Process finished with exit code 1
```

**Comment by valguss** [comment]
I've managed to get this working now but not sure how.

Cheers
